const firebaseConfig={apiKey:"AIzaSyAlAUnyCLOnTCMJoW3Ruix17gNDqAdzUhM",authDomain:"berbeltattoo.firebaseapp.com",projectId:"berbeltattoo",storageBucket:"berbeltattoo.firebasestorage.app",messagingSenderId:"805157565248",appId:"1:805157565248:web:1c9b455be4350baa5940a5"};
const initialDesigns=[
  ["001","Thanos","marvel","img/001.png","M-TH82"],["002","Iron Man","marvel","img/002.png","M-IR99"],["003","Loki","marvel","img/003.png","M-LK44"],["004","Spiderman","marvel","img/004.png","M-SP12"],["005","Dr. Strange","marvel","img/005.png","M-DR77"],["006","Black Panther","marvel","img/006.png","M-BP55"],["007","Thor","marvel","img/007.png","M-TH11"],["008","Deadpool","marvel","img/008.png","M-DP69"],
  ["009","Inazuma","anime","img/009.png","A-IN01"],["010","Zoro","anime","img/010.png","A-ZR33"],["011","Shin Chan","anime","img/011.png","A-SC55"],["012","Gyarados","anime","img/012.png","A-GY22"],["013","Naruto","anime","img/013.png","A-NA88"],["014","Dragon Ball","anime","img/014.png","A-DB07"],["015","Kitsune","anime","img/015.png","A-KI91"],["016","One Piece","anime","img/016.png","A-OP10"],
  ["017","Rey León","disney","img/017.png","D-RL30"],["018","Mickey","disney","img/018.png","D-MK01"],["019","Totoro","disney","img/019.png","D-TO44"],["020","La Bella y la Bestia","disney","img/020.png","D-RS22"],["021","Campanilla","disney","img/021.png","D-CP88"],["022","Toy Story","disney","img/022.png","D-ST66"],["023","Tigger","disney","img/023.png","D-AL99"],["024","Stitch","disney","img/024.png","D-CS00"]
];
const initialCategories=[{id:"marvel",nombre:"Marvel",ruletaActiva:true,precioRuleta:100},{id:"anime",nombre:"Anime",ruletaActiva:true,precioRuleta:100},{id:"disney",nombre:"Disney",ruletaActiva:true,precioRuleta:100}];
let db=null,storage=null,currentAdmin=null,usuariosData=[],videosData=[],designsData=[],categories=[...initialCategories],globalRoulettePrice=80,statusFilter="todos",panelStarted=false,unsubscribers=[],editingUserUid=null,pointsBusy=new Set(),storageOrphanItems=[];
const $=id=>document.getElementById(id);
document.addEventListener("DOMContentLoaded",()=>{if(typeof firebase==="undefined"){mostrarAcceso("login");toast("No se pudo conectar con Google");return;}try{firebase.initializeApp(firebaseConfig);db=firebase.firestore();if(firebase.storage)storage=firebase.storage();firebase.auth().onAuthStateChanged(validarAcceso);$("design-image-url").addEventListener("input",actualizarVistaPrevia);$("design-image-file").addEventListener("change",actualizarVistaPreviaArchivo);}catch(error){console.error(error);mostrarAcceso("login");}});

async function validarAcceso(user){if(!user){currentAdmin=null;detenerPanel();mostrarAcceso("login");return;}try{const doc=await db.collection("usuarios").doc(user.uid).get();if(doc.exists&&doc.data().rol==="admin"){currentAdmin=user;mostrarPanel();await iniciarPanel();}else{detenerPanel();$("denied-email").textContent=user.email||"Cuenta sin permiso";mostrarAcceso("denied");}}catch(error){console.error(error);$("denied-email").textContent="No se pudo comprobar el permiso.";mostrarAcceso("denied");}}
function mostrarAcceso(view){$("access-screen").classList.remove("hidden");$("admin-app").classList.add("hidden");$("access-loading").classList.add("hidden");$("access-login").classList.toggle("hidden",view!=="login");$("access-denied").classList.toggle("hidden",view!=="denied");}
function mostrarPanel(){$("access-screen").classList.add("hidden");$("admin-app").classList.remove("hidden");$("admin-name").textContent=currentAdmin.displayName||"Administrador";$("admin-email").textContent=currentAdmin.email||"";$("admin-avatar").src=currentAdmin.photoURL||"img/logo w.png";}
function loginAdmin(){firebase.auth().signInWithPopup(new firebase.auth.GoogleAuthProvider()).catch(()=>toast("No se pudo iniciar sesión"));}function cambiarCuenta(){firebase.auth().signOut().then(loginAdmin);}function logoutAdmin(){firebase.auth().signOut().then(()=>location.href="index.html");}

async function iniciarPanel(){if(panelStarted)return;panelStarted=true;try{await asegurarDatosIniciales();}catch(error){console.error(error);toast("No se pudo preparar el catálogo dinámico");}
  unsubscribers.push(db.collection("disenos").onSnapshot(snapshot=>{designsData=[];snapshot.forEach(doc=>designsData.push({id:doc.id,...doc.data()}));designsData.sort((a,b)=>(Number(a.orden)||9999)-(Number(b.orden)||9999)||(a.nombre||"").localeCompare(b.nombre||"","es"));renderizarTatuajesAdmin();actualizarEstadisticas();},()=>toast("No se pudieron cargar los diseños")));
  unsubscribers.push(db.collection("configuracion").doc("catalogo").onSnapshot(doc=>{if(doc.exists){const d=doc.data();categories=Array.isArray(d.categorias)&&d.categorias.length?d.categorias:initialCategories;globalRoulettePrice=Number(d.precioRuletaTotal)||80;}renderizarCategoriasAdmin();rellenarSelectCategorias();renderizarTatuajesAdmin();},()=>toast("No se pudieron cargar las categorías")));
  unsubscribers.push(db.collection("usuarios").onSnapshot(snapshot=>{usuariosData=[];snapshot.forEach(doc=>usuariosData.push({uid:doc.id,...doc.data()}));usuariosData.sort((a,b)=>(a.nombre||a.email||"").localeCompare(b.nombre||b.email||"","es"));renderizarUsuarios();},()=>toast("No se pudieron cargar las cuentas")));
  unsubscribers.push(db.collection("videos").onSnapshot(snapshot=>{videosData=[];snapshot.forEach(doc=>videosData.push({id:doc.id,...doc.data()}));videosData.sort((a,b)=>(b.fecha?.seconds||0)-(a.fecha?.seconds||0));renderizarVideosAdmin();},()=>toast("No se pudieron cargar los vídeos")));
}
async function asegurarDatosIniciales(){const configRef=db.collection("configuracion").doc("catalogo"),config=await configRef.get();if(!config.exists)await configRef.set({categorias:initialCategories,precioRuletaTotal:80});const one=await db.collection("disenos").limit(1).get();if(!one.empty)return;const inventory=await db.collection("inventario").doc("main").get(),cloud=inventory.exists?inventory.data():{},batch=db.batch();initialDesigns.forEach((d,index)=>{const legacy=cloud[Number(d[0])]||cloud[d[0]]||{};batch.set(db.collection("disenos").doc(d[0]),{nombre:d[1],cat:d[2],img:d[3],pass:d[4],precio:Number(legacy.precio)||130,estado:legacy.estado==="vendido"?"vendido":"disponible",ruletas:["all",d[2]],orden:index+1,creado:firebase.firestore.FieldValue.serverTimestamp()});});await batch.commit();}
function detenerPanel(){unsubscribers.forEach(unsub=>{try{unsub();}catch(e){}});unsubscribers=[];panelStarted=false;}
function cambiarTab(tab){document.querySelectorAll(".panel-section").forEach(section=>section.classList.toggle("hidden",section.id!==`tab-${tab}`));document.querySelectorAll(".nav-item").forEach(button=>button.classList.toggle("active",button.dataset.tab===tab));window.scrollTo({top:0,behavior:"smooth"});}

function filtrarEstado(status){statusFilter=status;document.querySelectorAll("[data-status]").forEach(button=>button.classList.toggle("active",button.dataset.status===status));renderizarTatuajesAdmin();}
function renderizarTatuajesAdmin(){const grid=$("design-grid");if(!grid)return;const term=($("design-search")?.value||"").trim().toLocaleLowerCase("es"),items=designsData.filter(t=>(statusFilter==="todos"||t.estado===statusFilter)&&(t.nombre||"").toLocaleLowerCase("es").includes(term));if(!items.length){grid.innerHTML='<p class="empty-copy">No hay diseños que coincidan con este filtro.</p>';return;}grid.innerHTML=items.map(t=>{const cat=categories.find(c=>c.id===t.cat)?.nombre||t.cat,raffles=Array.isArray(t.ruletas)?t.ruletas:[];return `<article class="design-card"><div class="design-image"><img src="${escapeHtml(t.img||"img/logo b.png")}" alt="${escapeHtml(t.nombre||"")}" loading="lazy"><span class="status-badge ${t.estado==="vendido"?"reserved":""}">${t.estado==="vendido"?"Reservado":"Disponible"}</span></div><div class="design-body"><div class="design-title"><div><h3>${escapeHtml(t.nombre||"Sin nombre")}</h3><span>${escapeHtml(cat)} · ${raffles.length?`${raffles.length} ruleta(s)`:"Sin ruleta"}</span></div><button type="button" onclick="abrirEditorDiseno('${t.id}')">Editar</button></div><div class="price-editor"><input id="price-${t.id}" type="number" min="0" max="10000" step="5" value="${Number(t.precio)||0}" aria-label="Precio"><span>€</span><button type="button" onclick="guardarPrecioTattoo('${t.id}')">Guardar</button></div><button class="state-button ${t.estado==="vendido"?"activate":"reserve"}" type="button" onclick="toggleEstadoTattoo('${t.id}','${t.estado}')">${t.estado==="vendido"?"Volver a poner disponible":"Marcar como reservado"}</button></div></article>`;}).join("");}
function actualizarEstadisticas(){const available=designsData.filter(t=>t.estado!=="vendido").length,reserved=designsData.length-available,avg=designsData.length?Math.round(designsData.reduce((sum,t)=>sum+(Number(t.precio)||0),0)/designsData.length):0;$("stat-total").textContent=designsData.length;$("stat-available").textContent=available;$("stat-reserved").textContent=reserved;$("stat-price").textContent=`${avg} €`;}
async function guardarPrecioTattoo(id){const input=$(`price-${id}`),precio=Number.parseInt(input.value,10);if(!Number.isFinite(precio)||precio<0||precio>10000){toast("Introduce un precio válido");return;}try{await db.collection("disenos").doc(id).update({precio});toast("Precio actualizado");}catch(error){toast("No se pudo cambiar el precio");}}
async function toggleEstadoTattoo(id,estado){try{await db.collection("disenos").doc(id).update({estado:estado==="vendido"?"disponible":"vendido"});toast(estado==="vendido"?"Diseño disponible de nuevo":"Diseño marcado como reservado");}catch(error){toast("No se pudo cambiar el estado");}}

function abrirEditorDiseno(id=""){const design=id?designsData.find(d=>d.id===id):null;$("design-form").reset();$("design-id").value=design?.id||"";$("design-modal-title").textContent=design?"Editar diseño":"Nuevo diseño";rellenarSelectCategorias();$("design-name").value=design?.nombre||"";$("design-category").value=design?.cat||categories[0]?.id||"";$("design-price").value=Number(design?.precio)||130;$("design-status").value=design?.estado||"disponible";$("design-image-url").value=design?.img||"";$("design-raffle-all").checked=design?design.ruletas?.includes("all"):true;$("design-raffle-category").checked=design?design.ruletas?.includes(design.cat):true;$("design-delete").classList.toggle("hidden",!design);$("design-image-preview").src=design?.img||"img/logo b.png";actualizarEtiquetaRuletaCategoria();$("design-modal").classList.remove("hidden");}
function cerrarEditorDiseno(){$("design-modal").classList.add("hidden");$("design-form").reset();}
function rellenarSelectCategorias(){const select=$("design-category");if(!select)return;const value=select.value;select.innerHTML=categories.map(c=>`<option value="${escapeHtml(c.id)}">${escapeHtml(c.nombre)}</option>`).join("");if(categories.some(c=>c.id===value))select.value=value;}
function actualizarEtiquetaRuletaCategoria(){$("design-raffle-category-label").textContent=`la ruleta de ${categories.find(c=>c.id===$("design-category").value)?.nombre||"su categoría"}`;}
function actualizarVistaPrevia(){const url=$("design-image-url").value.trim();if(url)$("design-image-preview").src=url;}
function actualizarVistaPreviaArchivo(){const file=$("design-image-file").files[0];if(file){if(file.size>20*1024*1024){toast("La imagen no puede superar 20 MB");$("design-image-file").value="";return;}$("design-image-preview").src=URL.createObjectURL(file);}}
async function optimizarImagen(file){if(file.size<900*1024||typeof createImageBitmap!=="function")return file;try{const bitmap=await createImageBitmap(file),scale=Math.min(1,1800/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise((resolve,reject)=>canvas.toBlob(result=>result?resolve(result):reject(new Error("No se pudo preparar la imagen")),"image/webp",.86));return new File([blob],`${file.name.replace(/\.[^.]+$/,"")}.webp`,{type:"image/webp"});}catch(error){console.warn("Se usará la imagen original",error);return file;}}
function mensajeErrorStorage(error){const code=error?.code||"";if(code.includes("unauthorized"))return"Firebase ha rechazado la subida. Hay que publicar las reglas de Storage.";if(code.includes("bucket-not-found")||code.includes("unknown"))return"Firebase Storage no está activado o el depósito no existe.";if(code.includes("canceled"))return"La subida tardó demasiado y se canceló. Prueba con otra imagen o utiliza una URL.";if(code.includes("retry-limit-exceeded"))return"La conexión agotó el tiempo de espera. Prueba de nuevo.";return error?.message||"No se pudo subir la imagen";}
function obtenerRutaStorage(designOrUrl){const path=typeof designOrUrl==="object"?designOrUrl?.storagePath:null,url=typeof designOrUrl==="string"?designOrUrl:designOrUrl?.img;if(path?.startsWith("designs/"))return path;if(!storage||!url||!url.includes("firebasestorage.googleapis.com"))return"";try{const ref=storage.refFromURL(url);return ref.fullPath.startsWith("designs/")?ref.fullPath:"";}catch{return"";}}
async function eliminarImagenGestionada(designOrUrl){const path=obtenerRutaStorage(designOrUrl);if(!path||!storage)return false;try{await storage.ref(path).delete();return true;}catch(error){if(error?.code==="storage/object-not-found")return true;console.warn("No se pudo limpiar la imagen",error);return false;}}
function formatearBytes(bytes){if(!Number.isFinite(bytes)||bytes<=0)return"0 MB";const units=["B","KB","MB","GB"],index=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),units.length-1);return`${(bytes/1024**index).toFixed(index>1?2:0)} ${units[index]}`;}
async function analizarAlmacenamiento(){const button=$("storage-scan"),summary=$("storage-summary"),clean=$("storage-clean");if(!storage){toast("Firebase Storage no está disponible");return;}button.disabled=true;button.textContent="Analizando…";clean.classList.add("hidden");try{const [result,designSnapshot]=await Promise.all([storage.ref("designs").listAll(),db.collection("disenos").get()]),items=await Promise.all(result.items.map(async ref=>({ref,path:ref.fullPath,metadata:await ref.getMetadata()}))),usedPaths=new Set();designSnapshot.forEach(doc=>{const path=obtenerRutaStorage(doc.data());if(path)usedPaths.add(path);});const total=items.reduce((sum,item)=>sum+(Number(item.metadata.size)||0),0);storageOrphanItems=items.filter(item=>!usedPaths.has(item.path));const orphanBytes=storageOrphanItems.reduce((sum,item)=>sum+(Number(item.metadata.size)||0),0),percent=Math.min(100,total/(5*1024**3)*100);summary.textContent=`${formatearBytes(total)} de 5 GB gratuitos (${percent<.01?"menos de 0,01":percent.toFixed(2)} %). ${items.length} archivo(s) almacenado(s).${storageOrphanItems.length?` ${storageOrphanItems.length} sin uso ocupan ${formatearBytes(orphanBytes)}.`:" No hay archivos sin uso."}`;clean.classList.toggle("hidden",!storageOrphanItems.length);}catch(error){console.error(error);summary.textContent="No se pudo analizar el almacenamiento.";toast(mensajeErrorStorage(error));}finally{button.disabled=false;button.textContent="Analizar de nuevo";}}
async function limpiarArchivosHuerfanos(){if(!storageOrphanItems.length||!confirm(`¿Borrar ${storageOrphanItems.length} archivo(s) que no utiliza ningún diseño?`))return;const button=$("storage-clean");button.disabled=true;button.textContent="Limpiando…";const results=await Promise.allSettled(storageOrphanItems.map(item=>item.ref.delete())),failed=results.filter(result=>result.status==="rejected").length;toast(failed?`Se limpiaron ${results.length-failed}; ${failed} no se pudieron borrar`:"Archivos sin uso eliminados");button.disabled=false;await analizarAlmacenamiento();}
function subirImagenStorage(file,button){return new Promise((resolve,reject)=>{const safe=file.name.replace(/[^a-z0-9._-]/gi,"-").toLowerCase(),ref=storage.ref(`designs/${Date.now()}-${safe}`),task=ref.put(file,{contentType:file.type,cacheControl:"public,max-age=31536000",customMetadata:{uploadedBy:currentAdmin?.uid||"admin"}}),timer=setTimeout(()=>task.cancel(),60000);task.on("state_changed",snapshot=>{const percent=Math.max(1,Math.round(snapshot.bytesTransferred/snapshot.totalBytes*100));button.textContent=`Subiendo imagen… ${percent}%`;},error=>{clearTimeout(timer);reject(new Error(mensajeErrorStorage(error)));},async()=>{clearTimeout(timer);try{resolve({url:await task.snapshot.ref.getDownloadURL(),path:task.snapshot.ref.fullPath});}catch(error){reject(new Error(mensajeErrorStorage(error)));}});});}
async function guardarDiseno(event){event.preventDefault();const button=$("design-save"),id=$("design-id").value,oldDesign=id?designsData.find(design=>design.id===id):null,cat=$("design-category").value,name=$("design-name").value.trim(),price=Number.parseInt($("design-price").value,10),file=$("design-image-file").files[0];if(!name||!cat||!Number.isFinite(price)){toast("Completa los datos obligatorios");return;}let img=$("design-image-url").value.trim(),uploaded=null;button.disabled=true;button.textContent=file?"Preparando imagen…":"Guardando…";try{if(file){if(!storage)throw new Error("Firebase Storage no está disponible. Usa una URL de imagen.");const optimized=await optimizarImagen(file);if(optimized.size>10*1024*1024)throw new Error("La imagen sigue superando 10 MB. Redúcela o utiliza una URL.");uploaded=await subirImagenStorage(optimized,button);img=uploaded.url;}if(!img)throw new Error("Añade una imagen o una URL");button.textContent="Guardando diseño…";const ruletas=[];if($("design-raffle-all").checked)ruletas.push("all");if($("design-raffle-category").checked)ruletas.push(cat);const data={nombre:name,cat,img,storagePath:uploaded?.path||obtenerRutaStorage(img)||null,precio:price,estado:$("design-status").value,ruletas,actualizado:firebase.firestore.FieldValue.serverTimestamp()};if(id)await db.collection("disenos").doc(id).update(data);else{data.orden=(designsData.at(-1)?.orden||0)+1;data.pass=crearCodigo();data.creado=firebase.firestore.FieldValue.serverTimestamp();await db.collection("disenos").add(data);}if(oldDesign&&obtenerRutaStorage(oldDesign)&&obtenerRutaStorage(oldDesign)!==data.storagePath)await eliminarImagenGestionada(oldDesign);cerrarEditorDiseno();toast(id?"Diseño actualizado":"Diseño añadido");}catch(error){console.error(error);toast(error.message||"No se pudo guardar el diseño");}finally{button.disabled=false;button.textContent="Guardar diseño";}}
function crearCodigo(){return`BT-${Math.random().toString(36).slice(2,8).toUpperCase()}`;}
async function eliminarDisenoActual(){const id=$("design-id").value,design=designsData.find(d=>d.id===id);if(!id||!design||!confirm(`¿Eliminar “${design.nombre}” del catálogo y borrar también su imagen subida? Esta acción no se puede deshacer.`))return;const button=$("design-delete"),hadManagedImage=!!obtenerRutaStorage(design);button.disabled=true;button.textContent="Eliminando…";try{await db.collection("disenos").doc(id).delete();const cleaned=hadManagedImage?await eliminarImagenGestionada(design):false;cerrarEditorDiseno();toast(!hadManagedImage?"Diseño eliminado":cleaned?"Diseño e imagen eliminados":"Diseño eliminado; la imagen queda pendiente de limpieza");}catch(error){console.error(error);toast("No se pudo eliminar el diseño");}finally{button.disabled=false;button.textContent="Eliminar diseño";}}

function renderizarCategoriasAdmin(){const list=$("categories-list");if(!list)return;$("global-roulette-price").value=globalRoulettePrice;list.innerHTML=categories.length?categories.map(c=>`<article class="category-row"><strong>${escapeHtml(c.nombre)}</strong><span class="slug">${escapeHtml(c.id)}</span><span class="category-state ${c.ruletaActiva?"active":""}">${c.ruletaActiva?"Activa":"Oculta"}</span><strong>${Number(c.precioRuleta)||0} €</strong><div class="category-row-actions"><button class="mini-button" type="button" onclick="abrirEditorCategoria('${c.id}')">Editar</button></div></article>`).join(""):'<p class="empty-copy">Todavía no hay categorías. Crea la primera para empezar.</p>';}
async function guardarConfiguracion(){await db.collection("configuracion").doc("catalogo").set({categorias:categories,precioRuletaTotal:globalRoulettePrice},{merge:true});}
async function guardarPrecioRuletaTotal(){const price=Number.parseInt($("global-roulette-price").value,10);if(!Number.isFinite(price)||price<0){toast("Introduce un precio válido");return;}globalRoulettePrice=price;try{await guardarConfiguracion();toast("Precio de la ruleta total actualizado");}catch(error){toast("No se pudo guardar");}}
function crearIdCategoria(name){let base=name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,32)||"categoria",id=base,n=2;while(categories.some(c=>c.id===id))id=`${base}-${n++}`;return id;}
function abrirEditorCategoria(id=""){const category=id?categories.find(c=>c.id===id):null;$("category-form").reset();$("category-id").value=category?.id||"";$("category-modal-title").textContent=category?"Editar categoría":"Nueva categoría";$("category-name").value=category?.nombre||"";$("category-price").value=Number(category?.precioRuleta)||100;$("category-raffle").checked=category?.ruletaActiva??true;$("category-delete").classList.toggle("hidden",!category);$("category-modal").classList.remove("hidden");setTimeout(()=>$("category-name").focus(),30);}
function cerrarEditorCategoria(){$("category-modal").classList.add("hidden");$("category-form").reset();}
async function guardarEditorCategoria(event){event.preventDefault();const currentId=$("category-id").value,name=$("category-name").value.trim(),price=Number.parseInt($("category-price").value,10),button=$("category-save");if(!name||!Number.isFinite(price)||price<0||price>10000){toast("Revisa el nombre y el precio");return;}const previous=categories.map(c=>({...c})),id=currentId||crearIdCategoria(name),data={id,nombre:name,ruletaActiva:$("category-raffle").checked,precioRuleta:price};categories=currentId?categories.map(c=>c.id===currentId?data:c):[...categories,data];button.disabled=true;button.textContent="Guardando…";try{await guardarConfiguracion();cerrarEditorCategoria();toast(currentId?"Categoría actualizada":"Categoría creada");}catch(error){categories=previous;renderizarCategoriasAdmin();toast("No se pudo guardar la categoría");}finally{button.disabled=false;button.textContent="Guardar categoría";}}
async function eliminarCategoriaActual(){const id=$("category-id").value,category=categories.find(c=>c.id===id),count=designsData.filter(d=>d.cat===id).length;if(!category)return;if(count){toast(`No se puede eliminar: contiene ${count} diseño(s)`);return;}if(!confirm(`¿Eliminar la categoría “${category.nombre}”?`))return;const previous=categories;categories=categories.filter(c=>c.id!==id);try{await guardarConfiguracion();cerrarEditorCategoria();toast("Categoría eliminada");}catch(error){categories=previous;renderizarCategoriasAdmin();toast("No se pudo eliminar la categoría");}}

function renderizarUsuarios(){const list=$("users-list");if(!list)return;const term=($("user-search")?.value||"").trim().toLocaleLowerCase("es"),users=usuariosData.filter(u=>`${u.nombre||""} ${u.email||""}`.toLocaleLowerCase("es").includes(term));if(!users.length){list.innerHTML='<p class="empty-copy">No hay cuentas que coincidan.</p>';return;}const order=["all",...categories.map(c=>c.id)];list.innerHTML=users.map(u=>{const admin=u.rol==="admin",self=u.uid===currentAdmin.uid,prizes=Object.entries(u.ruleta||{}).sort(([a],[b])=>order.indexOf(a)-order.indexOf(b)).map(([key,p])=>`<span>${key==="all"?"Total":escapeHtml(categories.find(c=>c.id===key)?.nombre||key)}: ${escapeHtml(p.nombre||"")}</span>`).join("");return `<article class="user-row"><div class="user-identity"><span class="user-avatar">${escapeHtml((u.nombre||u.email||"?").charAt(0).toUpperCase())}</span><div><strong>${escapeHtml(u.nombre||"Sin nombre")}</strong><small>${escapeHtml(u.email||"")}</small></div></div><span class="role-badge ${admin?"admin":""}">${admin?"Administrador":"Cliente"}</span><div class="prize-list">${prizes||'<span>Sin premios</span>'}</div><div class="coins-control"><button class="icon-button" type="button" ${pointsBusy.has(u.uid)?"disabled":""} onclick="cambiarMonedas('${u.uid}',-10)">−</button><strong>${Number(u.jimmyCoins)||0} JC</strong><button class="icon-button" type="button" ${pointsBusy.has(u.uid)?"disabled":""} onclick="cambiarMonedas('${u.uid}',10)">+</button></div><div class="row-actions"><button class="mini-button session" type="button" onclick="sumarJimmyCoinsSesion('${u.uid}')">Sesión → JC</button><button class="mini-button" type="button" onclick="editarMonedas('${u.uid}')">Editar JC</button>${self?'<span class="mini-button">Tu cuenta</span>':`<button class="mini-button ${admin?"danger":"promote"}" type="button" onclick="cambiarRol('${u.uid}','${admin?"cliente":"admin"}')">${admin?"Quitar admin":"Dar admin"}</button>`}</div></article>`;}).join("");}
async function cambiarMonedas(uid,cantidad){if(pointsBusy.has(uid))return;pointsBusy.add(uid);renderizarUsuarios();try{await db.runTransaction(async transaction=>{const ref=db.collection("usuarios").doc(uid),snapshot=await transaction.get(ref);if(!snapshot.exists)throw new Error();transaction.update(ref,{jimmyCoins:Math.max(0,(Number(snapshot.data().jimmyCoins)||0)+cantidad)});});toast("JimmyCoins actualizados");}catch(error){toast("No se pudieron actualizar los JimmyCoins");}finally{pointsBusy.delete(uid);renderizarUsuarios();}}
function jimmyCoinsPorSesion(precio){if(precio<=60)return 10;if(precio<=90)return 15;if(precio<=120)return 20;if(precio<=160)return 25;if(precio<=200)return 30;if(precio<=250)return 35;if(precio<=300)return 40;if(precio<400)return 50;return 60;}
async function sumarJimmyCoinsSesion(uid){const user=usuariosData.find(u=>u.uid===uid);if(!user)return;const value=prompt(`Precio pagado por la sesión de ${user.nombre||user.email} (€):`);if(value===null)return;const precio=Number(String(value).replace(",","."));if(!Number.isFinite(precio)||precio<=0){toast("Introduce un importe válido");return;}const coins=jimmyCoinsPorSesion(precio);if(!confirm(`Esta sesión suma ${coins} JimmyCoins. ¿Añadirlos a ${user.nombre||user.email}?`))return;pointsBusy.add(uid);renderizarUsuarios();try{await db.runTransaction(async transaction=>{const ref=db.collection("usuarios").doc(uid),snapshot=await transaction.get(ref);if(!snapshot.exists)throw new Error();transaction.update(ref,{jimmyCoins:(Number(snapshot.data().jimmyCoins)||0)+coins,ultimaSesion:{precio,jimmyCoins:coins,fecha:firebase.firestore.FieldValue.serverTimestamp()}});});toast(`+${coins} JimmyCoins añadidos`);}catch(error){console.error(error);toast("No se pudieron añadir los JimmyCoins de la sesión");}finally{pointsBusy.delete(uid);renderizarUsuarios();}}
function editarMonedas(uid){const user=usuariosData.find(u=>u.uid===uid);if(!user)return;editingUserUid=uid;$("points-user-label").textContent=`${user.nombre||"Usuario"} · ${user.email||""}`;$("points-input").value=String(Number(user.jimmyCoins)||0);$("points-modal").classList.remove("hidden");setTimeout(()=>$("points-input").select(),30);}function cerrarEditorPuntos(){editingUserUid=null;$("points-modal").classList.add("hidden");}
async function guardarEdicionPuntos(event){event.preventDefault();if(!editingUserUid)return;const total=Number.parseInt($("points-input").value,10);if(!Number.isFinite(total)||total<0||total>1000000){toast("Introduce una cantidad válida");return;}const uid=editingUserUid,button=$("points-save");button.disabled=true;try{await db.collection("usuarios").doc(uid).update({jimmyCoins:total});cerrarEditorPuntos();toast("JimmyCoins actualizados");}catch(error){toast("No se pudieron actualizar los JimmyCoins");}finally{button.disabled=false;}}
function cambiarRol(uid,rol){if(uid===currentAdmin.uid)return;const user=usuariosData.find(u=>u.uid===uid);if(!user||!confirm(`¿Cambiar el acceso de ${user.email||user.nombre}?`))return;db.collection("usuarios").doc(uid).update({rol}).then(()=>toast("Permiso actualizado")).catch(()=>toast("No se pudo cambiar el permiso"));}

function prepararUrlMultimedia(value){const clean=String(value).trim();if(!/^https:\/\//i.test(clean))throw new Error("El enlace debe empezar por https://");const url=new URL(clean),host=url.hostname.replace(/^www\./,"").toLowerCase();if(host==="instagram.com"){const parts=url.pathname.split("/").filter(Boolean),kind=parts[0],code=parts[1];if(!["p","reel","tv"].includes(kind)||!code)throw new Error("Copia el enlace de una publicación o reel público de Instagram");return`https://www.instagram.com/${kind}/${encodeURIComponent(code)}/`;}return clean;}
async function guardarVideo(event){event.preventDefault();const title=$("video-title").value.trim(),description=$("video-description").value.trim(),button=$("video-submit");let url;try{url=prepararUrlMultimedia($("video-url").value);}catch(error){toast(error.message);return;}button.disabled=true;try{await db.collection("videos").add({url,titulo:title,descripcion:description,fecha:firebase.firestore.FieldValue.serverTimestamp()});event.target.reset();toast("Contenido publicado");}catch(error){toast("No se pudo publicar el contenido");}finally{button.disabled=false;}}
function renderizarVideosAdmin(){const list=$("videos-list");if(!list)return;if(!videosData.length){list.innerHTML='<p class="empty-copy">Todavía no hay vídeos publicados.</p>';return;}list.innerHTML=videosData.map(v=>`<article class="video-row"><div><h3>${escapeHtml(v.titulo||"Sin título")}</h3><p>${escapeHtml(v.url||"")}</p></div><button type="button" onclick="borrarVideo('${v.id}')">Eliminar</button></article>`).join("");}function borrarVideo(id){if(!confirm("¿Eliminar este vídeo de la web?"))return;db.collection("videos").doc(id).delete().then(()=>toast("Vídeo eliminado")).catch(()=>toast("No se pudo eliminar"));}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));}let toastTimer;function toast(message){const el=$("admin-toast");el.textContent=message;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),3000);}
