const firebaseConfig={apiKey:"AIzaSyAlAUnyCLOnTCMJoW3Ruix17gNDqAdzUhM",authDomain:"berbeltattoo.firebaseapp.com",projectId:"berbeltattoo",storageBucket:"berbeltattoo.firebasestorage.app",messagingSenderId:"805157565248",appId:"1:805157565248:web:1c9b455be4350baa5940a5",measurementId:"G-71J3P635LN"};
const staticData=[
  {id:"001",nombre:"Thanos",cat:"marvel",img:"img/001.png",pass:"M-TH82"},{id:"002",nombre:"Iron Man",cat:"marvel",img:"img/002.png",pass:"M-IR99"},{id:"003",nombre:"Loki",cat:"marvel",img:"img/003.png",pass:"M-LK44"},{id:"004",nombre:"Spiderman",cat:"marvel",img:"img/004.png",pass:"M-SP12"},{id:"005",nombre:"Dr. Strange",cat:"marvel",img:"img/005.png",pass:"M-DR77"},{id:"006",nombre:"Black Panther",cat:"marvel",img:"img/006.png",pass:"M-BP55"},{id:"007",nombre:"Thor",cat:"marvel",img:"img/007.png",pass:"M-TH11"},{id:"008",nombre:"Deadpool",cat:"marvel",img:"img/008.png",pass:"M-DP69"},
  {id:"009",nombre:"Inazuma",cat:"anime",img:"img/009.png",pass:"A-IN01"},{id:"010",nombre:"Zoro",cat:"anime",img:"img/010.png",pass:"A-ZR33"},{id:"011",nombre:"Shin Chan",cat:"anime",img:"img/011.png",pass:"A-SC55"},{id:"012",nombre:"Gyarados",cat:"anime",img:"img/012.png",pass:"A-GY22"},{id:"013",nombre:"Naruto",cat:"anime",img:"img/013.png",pass:"A-NA88"},{id:"014",nombre:"Dragon Ball",cat:"anime",img:"img/014.png",pass:"A-DB07"},{id:"015",nombre:"Kitsune",cat:"anime",img:"img/015.png",pass:"A-KI91"},{id:"016",nombre:"One Piece",cat:"anime",img:"img/016.png",pass:"A-OP10"},
  {id:"017",nombre:"Rey León",cat:"disney",img:"img/017.png",pass:"D-RL30"},{id:"018",nombre:"Mickey",cat:"disney",img:"img/018.png",pass:"D-MK01"},{id:"019",nombre:"Totoro",cat:"disney",img:"img/019.png",pass:"D-TO44"},{id:"020",nombre:"La Bella y la Bestia",cat:"disney",img:"img/020.png",pass:"D-RS22"},{id:"021",nombre:"Campanilla",cat:"disney",img:"img/021.png",pass:"D-CP88"},{id:"022",nombre:"Toy Story",cat:"disney",img:"img/022.png",pass:"D-ST66"},{id:"023",nombre:"Tigger",cat:"disney",img:"img/023.png",pass:"D-AL99"},{id:"024",nombre:"Stitch",cat:"disney",img:"img/024.png",pass:"D-CS00"}
];
const defaultCategories=[{id:"marvel",nombre:"Marvel",ruletaActiva:true,precioRuleta:100},{id:"anime",nombre:"Anime",ruletaActiva:true,precioRuleta:100},{id:"disney",nombre:"Disney",ruletaActiva:true,precioRuleta:100}];
let categories=[...defaultCategories],globalRoulettePrice=80,tattoos=staticData.map((t,i)=>({...t,estado:"disponible",precio:130,ruletas:["all",t.cat],orden:i+1})),videos=[],filtroActual="todos",catRandomSelect="marvel",mensajeActual="",db=null,currentUser=null,userData=null,unsubscribeUser=null,randomBusy=false,rouletteTimer=null,dynamicCatalog=false,rouletteKeyActual="",resultadoActualId="";
const $=id=>document.getElementById(id);
document.addEventListener("DOMContentLoaded",()=>{$("year").textContent=new Date().getFullYear();renderizarCategorias();renderizarCatalogo();iniciarFirebase();document.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelectorAll(".modal:not(.hidden)").forEach(m=>m.classList.add("hidden"));});document.querySelectorAll(".modal").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)m.classList.add("hidden");}));});

function iniciarFirebase(){if(typeof firebase==="undefined")return;try{firebase.initializeApp(firebaseConfig);db=firebase.firestore();
  firebase.auth().onAuthStateChanged(user=>{if(unsubscribeUser){unsubscribeUser();unsubscribeUser=null;}currentUser=user&&!user.isAnonymous?user:null;$("btn-login").classList.toggle("hidden",!!currentUser);$("user-info").classList.toggle("hidden",!currentUser);if(!currentUser){userData=null;$("admin-link").classList.add("hidden");return;}$("user-name").textContent=(currentUser.displayName||"Mi cuenta").split(" ")[0];$("user-pic").src=currentUser.photoURL||"img/logo w.png";const ref=db.collection("usuarios").doc(currentUser.uid);unsubscribeUser=ref.onSnapshot(doc=>{if(doc.exists){userData=doc.data();$("user-coins").textContent=userData.jimmyCoins||0;$("admin-link").classList.toggle("hidden",userData.rol!=="admin");actualizarEstadoBotonesRandom();actualizarPerfilJimmyCoins();}else ref.set({nombre:currentUser.displayName||"Sin nombre",email:currentUser.email||"",jimmyCoins:0,rol:"cliente",fechaRegistro:firebase.firestore.FieldValue.serverTimestamp()});});});
  db.collection("configuracion").doc("catalogo").onSnapshot(doc=>{if(doc.exists){const data=doc.data();categories=Array.isArray(data.categorias)&&data.categorias.length?data.categorias:defaultCategories;globalRoulettePrice=Number(data.precioRuletaTotal)||80;renderizarCategorias();renderizarCatalogo();}});
  db.collection("disenos").onSnapshot(snapshot=>{if(snapshot.empty)return;dynamicCatalog=true;tattoos=[];snapshot.forEach(doc=>{const d=doc.data();tattoos.push({id:doc.id,nombre:d.nombre||"Sin nombre",cat:d.cat||"sin-categoria",img:d.img||"img/logo b.png",pass:d.pass||crearCodigo(doc.id),estado:d.estado==="vendido"?"vendido":"disponible",precio:Number(d.precio)||0,ruletas:Array.isArray(d.ruletas)?d.ruletas:[],orden:Number(d.orden)||9999});});tattoos.sort((a,b)=>a.orden-b.orden||a.nombre.localeCompare(b.nombre,"es"));renderizarCatalogo();},()=>{});
  db.collection("inventario").doc("main").onSnapshot(doc=>{if(dynamicCatalog||!doc.exists)return;const cloud=doc.data();tattoos=staticData.map((t,i)=>({...t,estado:cloud[Number(t.id)]?.estado||cloud[t.id]?.estado||"disponible",precio:cloud[Number(t.id)]?.precio||cloud[t.id]?.precio||130,ruletas:["all",t.cat],orden:i+1}));renderizarCatalogo();});
  db.collection("videos").onSnapshot(snapshot=>{videos=[];snapshot.forEach(doc=>videos.push({id:doc.id,...doc.data()}));videos.sort((a,b)=>(b.fecha?.seconds||0)-(a.fecha?.seconds||0));renderizarVideos();},()=>renderizarVideos());
}catch(error){console.warn("Sincronización no disponible",error);}}

function renderizarCategorias(){const filters=$("category-filters");if(filters){filters.innerHTML=[{id:"todos",nombre:"Todos"},...categories].map((c,i)=>`<button class="filter-btn ${c.id===filtroActual?"active":""}" type="button" data-cat="${escapeHtml(c.id)}" onclick="filtrarCategoria('${escapeAttr(c.id)}')">${escapeHtml(c.nombre)}</button>`).join("");}
  const active=categories.filter(c=>c.ruletaActiva);if(!active.some(c=>c.id===catRandomSelect))catRandomSelect=active[0]?.id||"";const tabs=$("random-tabs");if(tabs)tabs.innerHTML=active.length?active.map(c=>`<button id="btn-rand-${escapeHtml(c.id)}" class="cat-rand-btn ${c.id===catRandomSelect?"active":""}" type="button" onclick="seleccionarCatRandom('${escapeAttr(c.id)}')">${escapeHtml(c.nombre)}</button>`).join(""):'<p class="empty-state">No hay ruletas por categoría activas.</p>';$("total-roulette-price").textContent=`${globalRoulettePrice} €`;actualizarPrecioCategoria();}
function renderizarCatalogo(){const grid=$("grid-tattoos");if(!grid)return;const term=($("buscador")?.value||"").trim().toLocaleLowerCase("es");const items=tattoos.filter(t=>(filtroActual==="todos"||t.cat===filtroActual)&&t.nombre.toLocaleLowerCase("es").includes(term));$("catalog-status").textContent=`${items.length} ${items.length===1?"diseño":"diseños"} en esta selección`;if(!items.length){grid.innerHTML='<p class="empty-state">No hay diseños que coincidan. Prueba con otra búsqueda.</p>';return;}grid.innerHTML=items.map(t=>{const sold=t.estado==="vendido";return `<article class="tattoo-card"><div class="tattoo-image"><img src="${escapeHtml(t.img)}" alt="Diseño ${escapeHtml(t.nombre)}" loading="lazy"><span class="tattoo-number">N.º ${escapeHtml(String(t.id))}</span>${sold?'<div class="sold-mark">Pieza reservada</div>':""}</div><div class="tattoo-info"><div><h3>${escapeHtml(t.nombre)}</h3><p>${escapeHtml(nombreCategoria(t.cat))} · diseño único</p></div><span class="tattoo-price">${t.precio} €</span><button class="reserve-button" type="button" ${sold?"disabled":""} onclick="abrirModalReserva('${escapeAttr(String(t.id))}','${escapeAttr(t.nombre)}',${t.precio},null)"><span>${sold?"No disponible":"Reservar esta pieza"}</span><span>→</span></button></div></article>`;}).join("");}
function filtrarCategoria(cat){filtroActual=cat;renderizarCategorias();renderizarCatalogo();}function nombreCategoria(id){return categories.find(c=>c.id===id)?.nombre||id;}function crearCodigo(id){return`BT-${String(id).replace(/[^a-z0-9]/gi,"").slice(-6).toUpperCase()}`;}
function datosInstagram(value=""){try{const url=new URL(String(value).trim()),host=url.hostname.replace(/^www\./,"").toLowerCase(),parts=url.pathname.split("/").filter(Boolean),kind=parts[0],code=parts[1];if(host==="instagram.com"&&["p","reel","tv"].includes(kind)&&code)return{kind,page:`https://www.instagram.com/${kind}/${encodeURIComponent(code)}/`,embed:`https://www.instagram.com/${kind}/${encodeURIComponent(code)}/embed/`};}catch(e){}return null;}
function renderizarVideos(){const grid=$("grid-videos");if(!grid)return;if(!videos.length){grid.innerHTML='<p class="empty-state">Próximamente compartiremos nuevos procesos desde el estudio.</p>';return;}grid.innerHTML=videos.map(v=>{const instagram=datosInstagram(v.url),mediaClass=instagram?`instagram-embed-wrap ${instagram.kind==="p"?"instagram-post":"instagram-reel"}`:"";return`<article class="video-card"><div class="video-media ${mediaClass}">${videoSeguro(v.url)}</div><div class="video-copy"><h3>${escapeHtml(v.titulo||"Desde el estudio")}</h3><p>${escapeHtml(v.descripcion||"")}</p>${instagram?`<a class="instagram-link" href="${instagram.page}" target="_blank" rel="noopener noreferrer">Ver en Instagram →</a>`:""}</div></article>`;}).join("");}
function videoSeguro(url=""){const clean=String(url).trim(),instagram=datosInstagram(clean);if(instagram)return `<iframe src="${instagram.embed}" title="Contenido de Instagram de Berbel Tattoo" loading="lazy" scrolling="no" allowtransparency="true" allowfullscreen></iframe>`;let embed="",path="";try{const u=new URL(clean);path=u.pathname.toLowerCase();if(u.hostname.includes("youtube.com")){const id=u.searchParams.get("v")||u.pathname.split("/").filter(Boolean).pop();if(id)embed=`https://www.youtube.com/embed/${encodeURIComponent(id)}`;}else if(u.hostname==="youtu.be"){const id=u.pathname.split("/").filter(Boolean)[0];if(id)embed=`https://www.youtube.com/embed/${encodeURIComponent(id)}`;}}catch(e){}if(embed)return `<iframe src="${embed}" title="Vídeo de Berbel Tattoo" loading="lazy" allowfullscreen></iframe>`;if(/^https:\/\//i.test(clean)&&/\.(jpe?g|png|webp|gif)$/.test(path))return `<img src="${escapeHtml(clean)}" alt="Contenido de Berbel Tattoo" loading="lazy">`;if(/^https:\/\//i.test(clean))return `<video controls preload="metadata"><source src="${escapeHtml(clean)}"></video>`;return '<div class="empty-state">Contenido no disponible</div>';}
function cambiarVista(v){if(v!=="random")return;volverMenuRandom();setTimeout(()=>$("vista-random").scrollIntoView({behavior:"smooth"}),20);}function proveedorGoogle(){const provider=new firebase.auth.GoogleAuthProvider();provider.setCustomParameters({prompt:"select_account"});return provider;}function loginGoogle(){if(!db||typeof firebase==="undefined"){mostrarToast("La cuenta no está disponible en este momento");return;}firebase.auth().signInWithPopup(proveedorGoogle()).catch(()=>mostrarToast("No se pudo iniciar sesión"));}function cambiarCuentaGoogle(){if(typeof firebase==="undefined")return;firebase.auth().signInWithPopup(proveedorGoogle()).then(()=>cerrarModal("modal-perfil")).catch(()=>mostrarToast("No se pudo cambiar de cuenta"));}function logoutGoogle(){if(typeof firebase!=="undefined")firebase.auth().signOut().then(()=>cerrarModal("modal-perfil"));}

function manejarClickRuleta(modo){if(randomBusy)return;if(!currentUser||!userData){mostrarToast("Inicia sesión para usar la ruleta");loginGoogle();return;}const key=modo==="all"?"all":catRandomSelect;rouletteKeyActual=key;if(userData.ruleta?.[key]){const d=userData.ruleta[key];mostrarResultado(d.id,d.precio,d.pass,key,d.nombre,d.img);return;}iniciarRuleta(modo);}
function iniciarRuleta(modo){const key=modo==="all"?"all":catRandomSelect,pool=tattoos.filter(t=>t.estado==="disponible"&&t.ruletas.includes(key));if(!pool.length){mostrarToast("No hay diseños disponibles en esta ruleta");return;}if(!db||!currentUser){mostrarToast("No se pudo conectar con el juego. Prueba de nuevo");return;}rouletteKeyActual=key;randomBusy=true;actualizarBloqueoRuleta();$("random-options").classList.add("hidden");$("random-result").classList.add("hidden");$("random-loading").classList.remove("hidden");iniciarAnimacionRuleta(pool);setTimeout(async()=>{clearInterval(rouletteTimer);const price=modo==="all"?globalRoulettePrice:(Number(categories.find(c=>c.id===catRandomSelect)?.precioRuleta)||100);try{const result=await asignarPremioUnaSolaVez(key,pool,price);mostrarResultado(result.id,result.precio,result.pass,key,result.nombre,result.img);}catch(error){console.error(error);randomBusy=false;volverMenuRandom();mostrarToast("No se pudo guardar el premio. No se ha perdido ninguna tirada");}},2250);}
function iniciarAnimacionRuleta(pool){let index=Math.floor(Math.random()*pool.length);const image=$("random-preview-img"),name=$("random-preview-name"),show=()=>{const item=pool[index++%pool.length];image.src=item.img;name.textContent=item.nombre;};show();rouletteTimer=setInterval(show,105);}
async function asignarPremioUnaSolaVez(key,pool,price){const elegir=()=>{const chosen=pool[Math.floor(Math.random()*pool.length)];return{id:chosen.id,precio:price,pass:chosen.pass||crearCodigo(chosen.id),nombre:chosen.nombre,img:chosen.img};},ref=db.collection("usuarios").doc(currentUser.uid);return db.runTransaction(async transaction=>{const snapshot=await transaction.get(ref);if(!snapshot.exists)throw new Error("Cuenta no disponible");const existing=snapshot.data()?.ruleta?.[key];if(existing)return existing;const prize=elegir();transaction.update(ref,{[`ruleta.${key}`]:prize});return prize;});}
async function recuperarDisenoResultado(id,price,pass){if(!db)return;try{const snapshot=await db.collection("disenos").doc(String(id)).get();if(!snapshot.exists||resultadoActualId!==String(id))return;const data=snapshot.data(),nombre=data.nombre||"Tu diseño",img=data.img||"";if(img){$("res-img").src=img;$("res-img").alt=`Diseño ${nombre}`;}$("res-nombre").textContent=nombre;const claim=$("btn-res-claim");claim.disabled=false;claim.textContent="Reservar";claim.onclick=()=>abrirModalReserva(id,nombre,price,pass);}catch(error){console.warn("No se pudo recuperar la imagen del premio",error);}}
function mostrarResultado(id,price,pass,key=rouletteKeyActual,fallbackName="Tu diseño",fallbackImg=""){const t=tattoos.find(x=>String(x.id)===String(id)),img=t?.img||fallbackImg;rouletteKeyActual=key;resultadoActualId=String(id);randomBusy=false;clearInterval(rouletteTimer);actualizarBloqueoRuleta();$("random-loading").classList.add("hidden");$("random-options").classList.add("hidden");$("random-result").classList.remove("hidden");$("res-nombre").textContent=t?.nombre||fallbackName;$("res-precio").textContent=`${price} €`;$("res-pass").textContent=pass||"—";if(img){$("res-img").src=img;$("res-img").alt=`Diseño ${t?.nombre||fallbackName}`;}else{$("res-img").removeAttribute("src");$("res-img").alt="Cargando imagen del diseño";}const claim=$("btn-res-claim");claim.disabled=!t;claim.textContent=t?"Reservar":"Cargando diseño…";claim.onclick=t?()=>abrirModalReserva(t.id,t.nombre,price,pass):null;if(!t)recuperarDisenoResultado(id,price,pass);actualizarBotonCanje();}
function actualizarBloqueoRuleta(){document.querySelectorAll("#random-options button").forEach(button=>button.disabled=randomBusy);}
function actualizarBotonCanje(){const button=$("btn-reroll");if(!button)return;const coins=Number(userData?.jimmyCoins)||0,candidates=tattoos.filter(t=>t.estado==="disponible"&&t.ruletas.includes(rouletteKeyActual)&&String(t.id)!==resultadoActualId);button.classList.toggle("hidden",!currentUser||!rouletteKeyActual);button.disabled=randomBusy||coins<20||!candidates.length;button.querySelector("span:last-child").textContent=!candidates.length?"No hay otra pieza disponible":coins<20?`Te faltan ${20-coins} JimmyCoins`:`Nueva tirada · 20 JimmyCoins`;}
async function canjearNuevaTirada(){if(randomBusy||!db||!currentUser||!rouletteKeyActual)return;const coins=Number(userData?.jimmyCoins)||0,pool=tattoos.filter(t=>t.estado==="disponible"&&t.ruletas.includes(rouletteKeyActual)&&String(t.id)!==resultadoActualId);if(coins<20){mostrarToast(`Te faltan ${20-coins} JimmyCoins`);return;}if(!pool.length){mostrarToast("No hay otra pieza disponible en esta ruleta");return;}if(!confirm("¿Usar 20 JimmyCoins para conseguir una nueva tirada?"))return;randomBusy=true;actualizarBloqueoRuleta();actualizarBotonCanje();$("random-result").classList.add("hidden");$("random-loading").classList.remove("hidden");iniciarAnimacionRuleta(pool);const key=rouletteKeyActual,price=key==="all"?globalRoulettePrice:(Number(categories.find(c=>c.id===key)?.precioRuleta)||100),ref=db.collection("usuarios").doc(currentUser.uid);try{const result=await db.runTransaction(async transaction=>{const snapshot=await transaction.get(ref);if(!snapshot.exists)throw new Error("Cuenta no disponible");const data=snapshot.data(),saldo=Number(data.jimmyCoins)||0;if(saldo<20||!data.ruleta?.[key])throw new Error("Saldo o premio no válido");const chosen=pool[Math.floor(Math.random()*pool.length)],prize={id:chosen.id,precio:price,pass:chosen.pass||crearCodigo(chosen.id),nombre:chosen.nombre,img:chosen.img};transaction.update(ref,{jimmyCoins:saldo-20,[`ruleta.${key}`]:prize});return{...prize,saldo:saldo-20};});await new Promise(resolve=>setTimeout(resolve,1500));userData={...userData,jimmyCoins:result.saldo,ruleta:{...(userData.ruleta||{}),[key]:result}};$("user-coins").textContent=result.saldo;mostrarResultado(result.id,result.precio,result.pass,key,result.nombre,result.img);mostrarToast("Nueva tirada canjeada por 20 JimmyCoins");}catch(error){console.error(error);clearInterval(rouletteTimer);randomBusy=false;volverMenuRandom();mostrarToast("No se pudo completar el canje. Tus JimmyCoins no se han perdido");}}
function seleccionarCatRandom(cat){catRandomSelect=cat;renderizarCategorias();actualizarEstadoBotonesRandom();}function actualizarPrecioCategoria(){$("category-roulette-price").textContent=`${Number(categories.find(c=>c.id===catRandomSelect)?.precioRuleta)||100} €`;}
function actualizarEstadoBotonesRandom(){if(!$("btn-spin-cat"))return;const total=userData?.ruleta?.all;$("txt-spin-all-title").textContent=total?"Ver mi premio":"Ruleta total";$("txt-spin-all-desc").textContent=total?"Tu pieza ya está guardada · otra tirada cuesta 20 JC":"Una pieza sorpresa del catálogo";const assigned=userData?.ruleta?.[catRandomSelect];$("btn-spin-cat").textContent=assigned?"Ver mi premio":"Girar la ruleta";actualizarPrecioCategoria();actualizarBotonCanje();}
function volverMenuRandom(){randomBusy=false;clearInterval(rouletteTimer);rouletteKeyActual="";resultadoActualId="";actualizarBloqueoRuleta();$("random-options").classList.remove("hidden");$("random-loading").classList.add("hidden");$("random-result").classList.add("hidden");$("btn-reroll")?.classList.add("hidden");actualizarEstadoBotonesRandom();}
function abrirModalReserva(id,nombre,precio,pass){mensajeActual=pass?`Hola, Berbel. Me ha tocado el diseño “${nombre}” con el código ${pass} por ${precio} €. Me gustaría reservarlo.`:`Hola, Berbel. Quiero reservar el diseño “${nombre}” (n.º ${String(id)}) por ${precio} €. ¿Hablamos de tamaño, zona y disponibilidad?`;$("modal-mensaje").textContent=mensajeActual;$("btn-copiar").textContent="Copiar mensaje";$("modal-reserva").classList.remove("hidden");}
async function copiarMensaje(){try{await navigator.clipboard.writeText(mensajeActual);$("btn-copiar").textContent="Mensaje copiado ✓";mostrarToast("Mensaje copiado");}catch(e){const range=document.createRange();range.selectNode($("modal-mensaje"));window.getSelection().removeAllRanges();window.getSelection().addRange(range);mostrarToast("Selecciona y copia el mensaje");}}
function proximaRecompensa(coins){if(coins<75)return{meta:75,nombre:"Mini tattoo gratis"};if(coins<100)return{meta:100,nombre:"Jimmy Ruleta"};if(coins<150)return{meta:150,nombre:"50 € de descuento"};return{meta:200,nombre:coins>=200?"Jimmy Jackpot desbloqueado":"Jimmy Jackpot"};}
function actualizarPerfilJimmyCoins(){if(!$("perfil-modal-coins"))return;const coins=Number(userData?.jimmyCoins)||0,next=proximaRecompensa(coins),progress=Math.min(100,coins/next.meta*100);$("perfil-modal-coins").textContent=coins;$("perfil-proxima-recompensa").textContent=next.nombre;$("perfil-recompensa-necesaria").textContent=coins>=200?"¡Ya puedes canjearlo!":`${next.meta} JC necesarios`;$("perfil-progreso-texto").textContent=`${Math.min(coins,next.meta)} / ${next.meta}`;$("perfil-barra").style.width=`${progress}%`;$("perfil-barra").parentElement.setAttribute("aria-valuenow",String(Math.min(coins,next.meta)));$("perfil-barra").parentElement.setAttribute("aria-valuemax",String(next.meta));}
function abrirPerfil(){if(!currentUser)return;$("perfil-modal-pic").src=currentUser.photoURL||"img/logo w.png";$("perfil-modal-nombre").textContent=currentUser.displayName||"Mi cuenta";$("perfil-modal-email").textContent=currentUser.email||"";actualizarPerfilJimmyCoins();$("modal-perfil").classList.remove("hidden");}function cerrarModal(id){$(id)?.classList.add("hidden");}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));}function escapeAttr(value){return String(value).replace(/\\/g,"\\\\").replace(/'/g,"\\'");}let toastTimer;function mostrarToast(text){const toast=$("toast");toast.textContent=text;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),2800);}
